Repository VanSubstance/To-the-North, pull requests merged in 2023-04, with the labels that each got.

#84 Feature/structure of body
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Resources/Images/Creatures/Human.meta
  TotheNorth/Assets/Resources/Images/Creatures/Human/Structure.png
  TotheNorth/Assets/Resources/Images/Creatures/Human/Structure.png.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scripts/Battles.meta
  TotheNorth/Assets/Scripts/Battles/Controllers.meta
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs.meta
  TotheNorth/Assets/Scripts/Battles/Controllers/PartHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/PartHitController.cs.meta
  TotheNorth/Assets/Scripts/Battles/Objects.meta
  TotheNorth/Assets/Scripts/Battles/Objects/PartType.cs
  TotheNorth/Assets/Scripts/Battles/Objects/PartType.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraTrackControlller.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserMoveController.cs
  TotheNorth/ProjectSettings/TagManager.asset
Labels: enhancement, Module Structure

#94 Add: LeftInventory
  TotheNorth/Assets/Prefabs/Items/ItemEquipmentPrefab.prefab
  TotheNorth/Assets/Prefabs/Modal/Window/InventoryWindowPrefab.prefab
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/WindowModalInventoryContentController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Components/Modals/Objects/InventorySlotController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
Labels: Module Structure, refactor

#96 Develop
  TotheNorth/Assets/Prefabs/Items/ItemEquipmentPrefab.prefab
  TotheNorth/Assets/Prefabs/Modal/Window/InventoryWindowPrefab.prefab
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/WindowModalInventoryContentController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Components/Modals/Objects/InventorySlotController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
Labels: Module Structure, refactor

#99 Feature/structure of item
  TotheNorth/Assets/Prefabs/Creatures/NPC Prefab.prefab
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemConsumablePrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemEquipmentPrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemGarodeungPrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemMaterialPrefab.prefab
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables/Test Consumable.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables/Test Consumable.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors/Armor Info.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors/Armor Info.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Garodeung.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Garodeung.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Traffic Sign.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Traffic Sign.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Npcs.meta
  TotheNorth/Assets/Resources/Data Objects/Npcs/Npc Test.asset
  TotheNorth/Assets/Resources/Data Objects/Npcs/Npc Test.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Far Swing.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Far Swing.asset.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/WindowModalInventoryContentController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs.meta
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMeleeController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemRangeController.cs
  TotheNorth/Assets/Scripts/Items/Objects/EquipmentType.cs
  TotheNorth/Assets/Scripts/Items/Objects/EquipmentType.cs.meta
  TotheNorth/Assets/Scripts/Items/Objects/ItemArmorInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemArmorInfo.cs.meta
  TotheNorth/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemConsumableInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemEquipmentInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemMaterialInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs.meta
  TotheNorth/Assets/Scripts/Users/Controllers/UserMouseController.cs
Labels: Module Structure, refactor

#100 Feature/structure of item (#99)
  TotheNorth/Assets/Prefabs/Creatures/NPC Prefab.prefab
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemConsumablePrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemEquipmentPrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemGarodeungPrefab.prefab
  TotheNorth/Assets/Prefabs/Items/ItemMaterialPrefab.prefab
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables/Test Consumable.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Consumables/Test Consumable.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors/Armor Info.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors/Armor Info.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Garodeung.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Garodeung.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Traffic Sign.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Materials/Traffic Sign.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Npcs.meta
  TotheNorth/Assets/Resources/Data Objects/Npcs/Npc Test.asset
  TotheNorth/Assets/Resources/Data Objects/Npcs/Npc Test.asset.meta
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Far Swing.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Far Swing.asset.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/WindowModalInventoryContentController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs.meta
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMeleeController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemRangeController.cs
  TotheNorth/Assets/Scripts/Items/Objects/EquipmentType.cs
  TotheNorth/Assets/Scripts/Items/Objects/EquipmentType.cs.meta
  TotheNorth/Assets/Scripts/Items/Objects/ItemArmorInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemArmorInfo.cs.meta
  TotheNorth/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemConsumableInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemEquipmentInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemMaterialInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs.meta
  TotheNorth/Assets/Scripts/Users/Controllers/UserMouseController.cs
Labels: Module Structure, refactor

#116 Feature/effect on hit
  TotheNorth/Assets/Prefabs/Commons/Filter For Screen Prefab.prefab
  TotheNorth/Assets/Prefabs/Commons/Filter For Screen Prefab.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit/On Hits.prefab
  TotheNorth/Assets/Prefabs/Commons/On Hit/On Hits.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit/OnHit.prefab
  TotheNorth/Assets/Prefabs/Commons/On Hit/OnHit.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/Static Game Manager.prefab
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Resources/Images/Commons/On Hit.png
  TotheNorth/Assets/Resources/Images/Commons/On Hit.png.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/PartHitController.cs
  TotheNorth/Assets/Scripts/Battles/Interfaces/ICreatureBattle.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraHitEffectController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraHitEffectController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitEffectController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitEffectController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitFilterController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitFilterController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/ScreenHitEffectManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/ScreenHitEffectManager.cs.meta
  TotheNorth/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserBaseController.cs
Labels: Module Structure

#117 Feature/effect on hit (#116)
  TotheNorth/Assets/Prefabs/Commons/Filter For Screen Prefab.prefab
  TotheNorth/Assets/Prefabs/Commons/Filter For Screen Prefab.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit/On Hits.prefab
  TotheNorth/Assets/Prefabs/Commons/On Hit/On Hits.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/On Hit/OnHit.prefab
  TotheNorth/Assets/Prefabs/Commons/On Hit/OnHit.prefab.meta
  TotheNorth/Assets/Prefabs/Commons/Static Game Manager.prefab
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Resources/Images/Commons/On Hit.png
  TotheNorth/Assets/Resources/Images/Commons/On Hit.png.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/PartHitController.cs
  TotheNorth/Assets/Scripts/Battles/Interfaces/ICreatureBattle.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraHitEffectController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraHitEffectController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitEffectController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitEffectController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitFilterController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/ScreenHitFilterController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/ScreenHitEffectManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/ScreenHitEffectManager.cs.meta
  TotheNorth/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserBaseController.cs
Labels: Module Structure

#118 Feature/ai enhancement
  TotheNorth/Assets/Resources/Data Objects/Monsters/Test.asset
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Commons/Constants/InGameStatus.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraHitEffectController.cs
  TotheNorth/Assets/Scripts/Creatures/Bases/Squads/AISquadBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Controllers/Creatures/MonsterBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Detections/Controllers/DetectionCompositeController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemRangeController.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserMoveController.cs
Labels: bug, Module Structure

#121 Feature/trajectory varietion
  TotheNorth/Assets/Prefabs/Battles/Trajectories.meta
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory Manager.prefab
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory Manager.prefab.meta
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory.prefab
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory.prefab.meta
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Swing.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Swing.asset.meta
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/ProjectileController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/TrajectoryController.cs
  TotheNorth/Assets/Scripts/Battles/Objects/ProjectileInfo.cs
  TotheNorth/Assets/Scripts/Battles/Objects/TrajectoryType.cs
  TotheNorth/Assets/Scripts/Battles/Objects/TrajectoryType.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraTrackControlller.cs
  TotheNorth/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Controllers/Conductions/Squads/AISquadCombatController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemRangeController.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs
Labels: Module Structure, refactor

#122 Feature/97 inventory container for item
  TotheNorth/Assets/Prefabs/Modal/Window/InventoryWindowPrefab.prefab
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs.meta
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventorySlotController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventorySlotController.cs.meta
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
Labels: Module Structure

#123 Develop
  TotheNorth/Assets/Prefabs/Battles/Trajectories.meta
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory Manager.prefab
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory Manager.prefab.meta
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory.prefab
  TotheNorth/Assets/Prefabs/Battles/Trajectories/Trajectory.prefab.meta
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Prefabs/Modal/Window/InventoryWindowPrefab.prefab
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Swing.asset
  TotheNorth/Assets/Resources/Data Objects/Projectiles/Swing.asset.meta
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Battles/Controllers/CreatureHitController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/ProjectileController.cs
  TotheNorth/Assets/Scripts/Battles/Controllers/TrajectoryController.cs
  TotheNorth/Assets/Scripts/Battles/Objects/ProjectileInfo.cs
  TotheNorth/Assets/Scripts/Battles/Objects/TrajectoryType.cs
  TotheNorth/Assets/Scripts/Battles/Objects/TrajectoryType.cs.meta
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraTrackControlller.cs
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs.meta
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventorySlotController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventorySlotController.cs.meta
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Controllers/Conductions/Squads/AISquadCombatController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemRangeController.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemWeaponInfo.cs
Labels: Module Structure

#127 Feature/97 inventory container for item 3
  TotheNorth/Assets/Prefabs/Items/Item Prefab.prefab
  TotheNorth/Assets/Resources/Data Objects/Items/Equipments/Armors/Armor Info.asset
  TotheNorth/Assets/Resources/Images/Items/DrumTong.png.meta
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemGenerateController.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
Labels: Module Structure

#133 Feature/movement dodge
  TotheNorth/Assets/Scripts/Users/Constants/ConditionConstraint.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserMoveController.cs
Labels: enhancement, Module Structure

#138 Feature/body temperature thirst hunger
  TotheNorth/Assets/Prefabs/Commons/Static Game Manager.prefab
  TotheNorth/Assets/Prefabs/Components/Bar/Bar with Background Prefab.prefab
  TotheNorth/Assets/Prefabs/Modal/Infos/Penal For Conditions.prefab
  TotheNorth/Assets/Prefabs/Modal/Infos/Penal For HpSp.prefab
  TotheNorth/Assets/Prefabs/Modal/Infos/Penal For HpSp.prefab.meta
  TotheNorth/Assets/Prefabs/Modal/Infos/Penal For Welfare.prefab
  TotheNorth/Assets/Prefabs/Modal/Infos/Penal For Welfare.prefab.meta
  TotheNorth/Assets/Resources/Images/Icons/Hunger.png
  TotheNorth/Assets/Resources/Images/Icons/Hunger.png.meta
  TotheNorth/Assets/Resources/Images/Icons/Temperature.png
  TotheNorth/Assets/Resources/Images/Icons/Temperature.png.meta
  TotheNorth/Assets/Resources/Images/Icons/Thirst.png
  TotheNorth/Assets/Resources/Images/Icons/Thirst.png.meta
  TotheNorth/Assets/Scenes/InGame/MainMenuScene.unity
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Commons/Constants/GlobalComponent.cs
  TotheNorth/Assets/Scripts/Commons/Constants/InGameStatus.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/CameraTrackControlller.cs
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/MainMenuManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/MainMenuManager.cs.meta
  TotheNorth/Assets/Scripts/Commons/Managers/UIManager.cs
  TotheNorth/Assets/Scripts/Commons/Managers/UIManager.cs.meta
  TotheNorth/Assets/Scripts/Components/Infos/Controllers/UIHpSpController.cs
  TotheNorth/Assets/Scripts/Components/Infos/Controllers/UIHpSpController.cs.meta
  TotheNorth/Assets/Scripts/Components/Infos/Controllers/UINumericController.cs
  TotheNorth/Assets/Scripts/Components/Infos/Controllers/UIWelfareController.cs
  TotheNorth/Assets/Scripts/Components/Infos/Controllers/UIWelfareController.cs.meta
  TotheNorth/Assets/Scripts/Components/Progress/Controllers/BarBaseController.cs
  TotheNorth/Assets/Scripts/Components/Progress/Objects/ProgressInfo.cs
  TotheNorth/Assets/Scripts/Creatures/Objects/CreatureInfo.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserBaseController.cs
  TotheNorth/Assets/Scripts/Users/Controllers/UserMouseController.cs
Labels: System structure, Module Structure, refactor

#143 Feature/item information when hovering
  TotheNorth/Assets/Prefabs/Commons/Static Game Manager.prefab
  TotheNorth/Assets/Prefabs/Modal/Item Info when Hovering.prefab
  TotheNorth/Assets/Prefabs/Modal/Item Info when Hovering.prefab.meta
  TotheNorth/Assets/Resources/DataObjects/Items/Consumables/Bullets/Wooden Arrow.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Consumables/Foods/CornSalad.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Equipments/Armors/Drumb.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Equipments/Weapons/Wooden Bow.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Materials/Garodeung.asset
  TotheNorth/Assets/Resources/DataObjects/Items/Materials/Traffic Sign.asset
  TotheNorth/Assets/Resources/DataObjects/Monsters/Items/Equipments/Armors/Drumb.asset
  TotheNorth/Assets/Resources/DataObjects/Monsters/Items/Equipments/Weapons/Test Gun.asset
  TotheNorth/Assets/Resources/DataObjects/Monsters/Items/Equipments/Weapons/Test Knife.asset
  TotheNorth/Assets/Resources/DataObjects/Monsters/Items/Equipments/Weapons/Wooden Bow.asset
  TotheNorth/Assets/Resources/Images/Items/Equipments/Magazines.meta
  TotheNorth/Assets/Resources/Meshs/SpriteOpacityMesh.mat
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scripts/Battles/Objects/AttackInfo.cs
  TotheNorth/Assets/Scripts/Commons/Constants/GlobalComponent.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/MouseTrackController.cs
  TotheNorth/Assets/Scripts/Commons/Controllers/MouseTrackController.cs.meta
  TotheNorth/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Components/Popups.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoArmorController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoArmorController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoBaseController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoBaseController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoBulletController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoBulletController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoConsumableController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoConsumableController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoEquipmentController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoEquipmentController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoFoodController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoFoodController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoMagazineController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoMagazineController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoMaterialController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoMaterialController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoWeaponController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/ByTypes/HoverItemInfoWeaponController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/HoverItemInfoContainerController.cs
  TotheNorth/Assets/Scripts/Components/Popups/Controllers/HoverItemInfoContainerController.cs.meta
  TotheNorth/Assets/Scripts/Components/Popups/Interfaces.meta
  TotheNorth/Assets/Scripts/Components/Popups/Interfaces/IHoverItemInfo.cs
  TotheNorth/Assets/Scripts/Components/Popups/Interfaces/IHoverItemInfo.cs.meta
  TotheNorth/Assets/Scripts/Creatures/Detections/Controllers/DetectionAimController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
  TotheNorth/Assets/Scripts/Items/Objects/Consumbables/ItemFoodInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/Equipments/ItemWeaponInfo.cs
  TotheNorth/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
  TotheNorth/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
  TotheNorth/ProjectSettings/TagManager.asset
Labels: Module Structure

#145 Feature/141 inventory equip item
  TotheNorth/Assets/Prefabs/Modal/Window/InventoryWindowPrefab.prefab
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scripts/Commons/Managers/DataManager.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/EquipmentSlotController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/EquipmentSlotController.cs.meta
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventoryContentController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Controllers/InventorySlotController.cs
  TotheNorth/Assets/Scripts/Components/Inventory/Manager/InventoryManager.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  TotheNorth/Assets/Scripts/Items/Abstracts/AbsItemController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemArmorController.cs
  TotheNorth/Assets/Scripts/Items/Controllers/ItemWeaponController.cs
Labels: enhancement, Module Structure, refactor

#148 Feature/map tiles for field + editoring02
  TotheNorth/Assets/Prefabs/Commons/Filter For Screen Prefab.prefab
  TotheNorth/Assets/Prefabs/Creatures/User Prefab.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/City.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/City.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/1.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/1.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/3.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/3.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/7.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/7.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/9.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/9.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/Horizontal01.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/Horizontal01.prefab.meta
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/Vertical01.prefab
  TotheNorth/Assets/Prefabs/Map/Obstacles/City/Walls/Vertical01.prefab.meta
  TotheNorth/Assets/Resources/Images/Maps/Obstacles/Walls.meta
  TotheNorth/Assets/Resources/Images/Maps/Obstacles/Walls/Horizontal Wall.png
  TotheNorth/Assets/Resources/Images/Maps/Obstacles/Walls/Horizontal Wall.png.meta
  TotheNorth/Assets/Resources/Images/Maps/Obstacles/Walls/Vertical Wall.png
  TotheNorth/Assets/Resources/Images/Maps/Obstacles/Walls/Vertical Wall.png.meta
  TotheNorth/Assets/Resources/Images/Maps/Tiles/Bg_01.asset
  TotheNorth/Assets/Resources/Images/Maps/Tiles/Bg_01.asset.meta
  TotheNorth/Assets/Resources/Images/Maps/Tiles/Bg_02.asset
  TotheNorth/Assets/Resources/Images/Maps/Tiles/Bg_02.asset.meta
  TotheNorth/Assets/Resources/Images/Maps/Tiles/PaleRoad.asset
  TotheNorth/Assets/Resources/Images/Maps/Tiles/PaleRoad.asset.meta
  TotheNorth/Assets/Resources/Palette/Obstacles.prefab
  TotheNorth/Assets/Resources/Palette/Tile.prefab
  TotheNorth/Assets/Resources/Palette/Tile.prefab.meta
  TotheNorth/Assets/Scenes/InGame/Map Editor.unity
  TotheNorth/Assets/Scenes/Sections/Home.unity
  TotheNorth/Assets/Scenes/Sections/Hospital/Floor_01.unity
  TotheNorth/Assets/Scripts/Creatures/Detections/Controllers/DetectionBaseController.cs
  TotheNorth/Assets/Scripts/Creatures/Detections/Controllers/DetectionPassiveController.cs
  TotheNorth/Assets/Scripts/Maps/Managers/ObstacleBundlingManager.cs
Labels: System structure, Module Structure

#154 Feature/ai refactoring all ai system 01
  To-the-North-3d/Assets/Prefabs/Creatures/Monster Prefab.prefab
  To-the-North-3d/Assets/Prefabs/Creatures/User Prefab.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Half Test.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Wall2.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Wall4.prefab
  To-the-North-3d/Assets/Resources/Materials.meta
  To-the-North-3d/Assets/Resources/Materials/CreatureCollider.physicMaterial
  To-the-North-3d/Assets/Resources/Materials/CreatureCollider.physicMaterial.meta
  To-the-North-3d/Assets/Resources/Meshs/EnemyDetectionMesh.mat
  To-the-North-3d/Assets/Scenes/SampleScene.meta
  To-the-North-3d/Assets/Scenes/SampleScene.unity
  To-the-North-3d/Assets/Scenes/SampleScene/NavMesh.asset
  To-the-North-3d/Assets/Scenes/SampleScene/NavMesh.asset.meta
  To-the-North-3d/Assets/Scripts/Creatures/Bases/Units/AIBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Bases/Units/RenewAIBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Bases/Units/RenewAIBaseController.cs.meta
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/MonsterBaseController.cs
  To-the-North-3d/Assets/Scripts/Users/Controllers/UserMoveController.cs
  To-the-North-3d/ProjectSettings/NavMeshAreas.asset
Labels: System structure

#160 Add: Particle for Suspicious
  To-the-North-3d/Assets/Prefabs/Events/Portal Prefab.prefab
  To-the-North-3d/Assets/Scenes/SampleScene.unity
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/AIBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionPassiveController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionSightController.cs
  To-the-North-3d/Assets/Scripts/Events/Abstracts/AbsEventBaseController.cs
  To-the-North-3d/Assets/Scripts/Events/Abstracts/AbsEventBaseController.cs.meta
  To-the-North-3d/Assets/Scripts/Events/Controllers/EventNpcController.cs
  To-the-North-3d/Assets/Scripts/Events/Controllers/EventPortalController.cs
  To-the-North-3d/Assets/Scripts/Events/Controllers/EventRootingController.cs
  To-the-North-3d/Assets/Scripts/Events/Interfaces/IEventInteraction.cs
Labels: enhancement, Module Structure

#164 Feature/creature refactoring
  To-the-North-3d/Assets/Prefabs/Creatures/Body Structures/Human/Visuals.prefab
  To-the-North-3d/Assets/Prefabs/Creatures/Monsters/Human.prefab
  To-the-North-3d/Assets/Prefabs/Creatures/User Prefab.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Base.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Base.prefab.meta
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Dig2.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Dig5.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Half Test.prefab
  To-the-North-3d/Assets/Prefabs/Map/Obstacles/Test/Hide Test.prefab
  To-the-North-3d/Assets/Resources/Meshs/SightUpper.mat
  To-the-North-3d/Assets/Scenes/SampleScene.unity
  To-the-North-3d/Assets/Scenes/SampleScene/NavMesh.asset
  To-the-North-3d/Assets/Scripts/Commons/Interfaces/IInteractionWithSight.cs
  To-the-North-3d/Assets/Scripts/Commons/Interfaces/IInteractionWithSight.cs.meta
  To-the-North-3d/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/AIBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/AbsCreatureBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/BodyRotateController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/MonsterBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/NpcBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionBaseController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionSightController.cs
  To-the-North-3d/Assets/Scripts/Events/Abstracts/AbsEventBaseController.cs
  To-the-North-3d/Assets/Scripts/Events/Interfaces/IEventInteraction.cs
Labels: enhancement, Module Structure

#166 Feature/inventory item interaction event03
  To-the-North-3d/.editorconfig
  To-the-North-3d/Assets/Prefabs/Items/Item Prefab.prefab
  To-the-North-3d/Assets/Prefabs/Modal/Window/Inventory/Containers/Container Blank.prefab
  To-the-North-3d/Assets/Prefabs/Modal/Window/Inventory/Containers/Content Blank.prefab
  To-the-North-3d/Assets/Prefabs/Modal/Window/Inventory/Containers/Contents/Content Blank.prefab
  To-the-North-3d/Assets/Prefabs/Modal/Window/Inventory/Containers/Contents/Content Blank.prefab.meta
  To-the-North-3d/Assets/Resources/DataObjects/Items/Consumables/Bullets/B-9-01.asset
  To-the-North-3d/Assets/Resources/DataObjects/Items/Equipments/Weapons/R-P-01.asset
  To-the-North-3d/Assets/Resources/DataObjects/Items/Equipments/Weapons/Wooden Bow.asset
  To-the-North-3d/Assets/Scenes/Inventory Dev.unity
  To-the-North-3d/Assets/Scripts/Commons/Constants/InGameStatus.cs
  To-the-North-3d/Assets/Scripts/Commons/Controllers/CameraTrackControlller.cs
  To-the-North-3d/Assets/Scripts/Commons/Managers/CommonGameManager.cs
  To-the-North-3d/Assets/Scripts/Commons/Managers/DataManager.cs
  To-the-North-3d/Assets/Scripts/Components/Conversations/Controllers/ConversationBaseController.cs
  To-the-North-3d/Assets/Scripts/Components/Conversations/Managers/ConversationManager.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Controllers/WindowBaseController.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/Contents/ContentEquipmentController.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/Contents/ContentSlotController.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/Contents/InventorySlotController.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/WindowInventoryController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Controllers/Creatures/BodyRotateController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionAimController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionPassiveController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Controllers/DetectionSightController.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Editors/DetectionPassiveEditor.cs
  To-the-North-3d/Assets/Scripts/Creatures/Detections/Editors/DetectionSightEditor.cs
  To-the-North-3d/Assets/Scripts/Events/Abstracts/AbsEventBaseController.cs
  To-the-North-3d/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemGenerateController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemWeaponController.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Consumbables/ItemBulletInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Consumbables/ItemConsumableInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Equipments/ItemMagazineInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Equipments/ItemWeaponInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/ItemInventoryInfo.cs
  To-the-North-3d/Assets/Scripts/Users/Controllers/ConditionController.cs
  To-the-North-3d/Assets/Scripts/Users/Controllers/UserBaseController.cs
  To-the-North-3d/Assets/Scripts/Users/Controllers/UserMouseController.cs
  To-the-North-3d/Assets/Scripts/Users/Controllers/UserMoveController.cs
  To-the-North-3d/Assets/Scripts/Users/Managers/ConditionManager.cs
  To-the-North-3d/Assets/TextMesh Pro/Fonts/Kor_01.asset
Labels: enhancement, Module Structure

#167 Feature/inventory item interaction event04
  To-the-North-3d/Assets/Scenes/Inventory Dev.unity
  To-the-North-3d/Assets/Scripts/Commons/Constants/InGameStatus.cs
  To-the-North-3d/Assets/Scripts/Commons/Managers/DataManager.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/Contents/InventorySlotController.cs
  To-the-North-3d/Assets/Scripts/Components/Windows/Inventory/Controllers/WindowInventoryController.cs
  To-the-North-3d/Assets/Scripts/Events/Controllers/EventNpcController.cs
  To-the-North-3d/Assets/Scripts/Items/Abstracts/AItemBaseController.cs
  To-the-North-3d/Assets/Scripts/Items/Abstracts/AbsItemController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemConsumableController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemEquipmentController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemMaterialController.cs
  To-the-North-3d/Assets/Scripts/Items/Controllers/ItemWeaponController.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Consumbables/ItemConsumableInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Equipments/ItemMagazineInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/Equipments/ItemWeaponInfo.cs
  To-the-North-3d/Assets/Scripts/Items/Objects/ItemBaseInfo.cs
Labels: Module Structure
